import type {
  ActivityEvent,
  Comment,
  Notification,
  Task,
  User,
} from "./types";

// Stable "now" anchored relative dates so seeded data always looks fresh.
const now = Date.now();
const days = (n: number) => new Date(now + n * 86_400_000).toISOString();

export const GOKUL_ID = "u_gokul";

export const SEED_USERS: User[] = [
  {
    id: GOKUL_ID,
    name: "Gokul Krishna",
    email: "gokul@company.com",
    avatarColor: "#6366f1",
    role: "admin",
  },
  {
    id: "u_aisha",
    name: "Aisha Verma",
    email: "aisha@company.com",
    avatarColor: "#ec4899",
    role: "requester",
    department: "Marketing",
  },
  {
    id: "u_daniel",
    name: "Daniel Cruz",
    email: "daniel@company.com",
    avatarColor: "#0ea5e9",
    role: "requester",
    department: "Sales",
  },
  {
    id: "u_meera",
    name: "Meera Nair",
    email: "meera@company.com",
    avatarColor: "#10b981",
    role: "requester",
    department: "Product",
  },
  {
    id: "u_tom",
    name: "Tom Becker",
    email: "tom@company.com",
    avatarColor: "#f59e0b",
    role: "requester",
    department: "People & Culture",
  },
  {
    id: "u_lena",
    name: "Lena Schmidt",
    email: "lena@company.com",
    avatarColor: "#8b5cf6",
    role: "requester",
    department: "Leadership",
  },
];

export const CURRENT_USER_ID = "u_aisha"; // demo: signed in as a requester

export const SEED_TASKS: Task[] = [
  {
    id: "t_1",
    reference: "GW-118",
    title: "Q3 Product Launch — LinkedIn campaign creatives",
    description:
      "We're launching the v3 platform on July 8. Need a coordinated set of 6 LinkedIn creatives: 1 hero announcement, 3 feature spotlights, 1 customer quote, and 1 'book a demo' CTA card. Must follow the new brand system and use the launch gradient. Copy will be supplied, you own layout + visual hierarchy.",
    businessObjective:
      "Drive demo signups for the v3 launch and establish the refreshed visual identity in-market.",
    status: "in_progress",
    priority: "critical",
    deliverableType: "linkedin_creative",
    department: "Marketing",
    requesterId: "u_aisha",
    contact: { name: "Aisha Verma", email: "aisha@company.com", phone: "+1 415 555 0142" },
    deadline: days(4),
    estimatedCompletion: days(3),
    effort: "large",
    tags: ["launch", "campaign", "linkedin"],
    pendingInfo: [],
    additionalNotes: "Hero card is the priority — needed first for the teaser post.",
    attachments: [
      {
        id: "a_1",
        name: "v3-brand-system.pdf",
        kind: "pdf",
        sizeLabel: "4.2 MB",
        url: "#",
        uploadedBy: "u_aisha",
        uploadedAt: days(-3),
      },
      {
        id: "a_2",
        name: "launch-copy-final.docx",
        kind: "doc",
        sizeLabel: "88 KB",
        url: "#",
        uploadedBy: "u_aisha",
        uploadedAt: days(-2),
      },
    ],
    references: [
      { id: "r_1", label: "Brand system (Figma)", url: "https://figma.com/file/brand", provider: "figma" },
      { id: "r_2", label: "Launch assets folder", url: "https://drive.google.com/launch", provider: "google_drive" },
    ],
    intakeScore: 92,
    createdAt: days(-3),
    updatedAt: days(-1),
    queueRank: 1,
  },
  {
    id: "t_2",
    reference: "GW-117",
    title: "Investor update deck — Q2 results",
    description:
      "Polish the 18-slide quarterly investor deck. Content is drafted in Google Slides; need visual design pass: consistent charts, data viz cleanup, cover + divider slides, and an appendix template. Board meeting is next week.",
    businessObjective:
      "Present Q2 performance to the board and current investors with a professional, on-brand deck.",
    status: "waiting_inputs",
    priority: "high",
    deliverableType: "presentation",
    department: "Leadership",
    requesterId: "u_lena",
    contact: { name: "Lena Schmidt", email: "lena@company.com", phone: "+1 415 555 0190" },
    deadline: days(6),
    estimatedCompletion: days(5),
    effort: "medium",
    tags: ["deck", "investor", "board"],
    pendingInfo: ["Final Q2 revenue numbers", "Updated org chart"],
    attachments: [],
    references: [
      { id: "r_3", label: "Draft deck (Slides)", url: "https://docs.google.com/presentation/d/draft", provider: "google_drive" },
    ],
    intakeScore: 71,
    createdAt: days(-5),
    updatedAt: days(-1),
    queueRank: 2,
  },
  {
    id: "t_3",
    reference: "GW-116",
    title: "Sales one-pager for enterprise prospects",
    description:
      "A clean, single-page PDF the AE team can attach to outbound emails. Should cover the 3 enterprise value props, a logo wall, and one ROI stat. Letter + A4 sizes.",
    businessObjective: "Increase reply rate on enterprise outbound by giving AEs a polished leave-behind.",
    status: "todo",
    priority: "high",
    deliverableType: "print_design",
    department: "Sales",
    requesterId: "u_daniel",
    contact: { name: "Daniel Cruz", email: "daniel@company.com", phone: "+1 415 555 0177" },
    deadline: days(8),
    estimatedCompletion: null,
    effort: "small",
    tags: ["sales", "one-pager", "enterprise"],
    pendingInfo: [],
    attachments: [],
    references: [
      { id: "r_4", label: "Approved logo wall", url: "https://dropbox.com/logos", provider: "dropbox" },
    ],
    intakeScore: 78,
    createdAt: days(-4),
    updatedAt: days(-2),
    queueRank: 3,
  },
  {
    id: "t_4",
    reference: "GW-115",
    title: "Onboarding welcome motion graphic",
    description:
      "A 15-second looping motion graphic for the new-hire welcome screen in our HR portal. Friendly, on-brand, no voiceover. Should feel warm and human.",
    businessObjective: "Improve first-day experience and reinforce employer brand for new joiners.",
    status: "backlog",
    priority: "medium",
    deliverableType: "motion_graphic",
    department: "People & Culture",
    requesterId: "u_tom",
    contact: { name: "Tom Becker", email: "tom@company.com" },
    deadline: days(20),
    estimatedCompletion: null,
    effort: "large",
    tags: ["motion", "hr", "onboarding"],
    pendingInfo: ["Final copy for the welcome line"],
    attachments: [],
    references: [
      { id: "r_5", label: "Moodboard", url: "https://youtu.be/example", provider: "youtube" },
    ],
    intakeScore: 64,
    createdAt: days(-7),
    updatedAt: days(-6),
    queueRank: 5,
  },
  {
    id: "t_5",
    reference: "GW-114",
    title: "Feature announcement — in-app banner asset",
    description:
      "Static banner for the dashboard announcing the new analytics module. 1200x300. Needs a small illustration and a CTA chip.",
    businessObjective: "Drive adoption of the new analytics module among existing users.",
    status: "review",
    priority: "medium",
    deliverableType: "website_asset",
    department: "Product",
    requesterId: "u_meera",
    contact: { name: "Meera Nair", email: "meera@company.com", phone: "+1 415 555 0133" },
    deadline: days(2),
    estimatedCompletion: days(1),
    effort: "small",
    tags: ["product", "banner", "in-app"],
    pendingInfo: [],
    attachments: [
      {
        id: "a_3",
        name: "banner-v2.png",
        kind: "image",
        sizeLabel: "640 KB",
        url: "#",
        uploadedBy: "u_gokul",
        uploadedAt: days(-1),
      },
    ],
    references: [],
    intakeScore: 80,
    createdAt: days(-6),
    updatedAt: days(0),
    queueRank: 4,
  },
  {
    id: "t_6",
    reference: "GW-113",
    title: "Recruiting event booth backdrop",
    description:
      "Large-format backdrop (3m x 2.25m) for the university recruiting fair. Bold, eye-catching, with the careers QR code.",
    businessObjective: "Attract top graduate talent at the autumn recruiting fair.",
    status: "approved",
    priority: "low",
    deliverableType: "event_collateral",
    department: "People & Culture",
    requesterId: "u_tom",
    contact: { name: "Tom Becker", email: "tom@company.com", phone: "+1 415 555 0155" },
    deadline: days(14),
    estimatedCompletion: days(2),
    effort: "medium",
    tags: ["event", "recruiting", "print"],
    pendingInfo: [],
    attachments: [
      {
        id: "a_4",
        name: "backdrop-final.pdf",
        kind: "pdf",
        sizeLabel: "12.1 MB",
        url: "#",
        uploadedBy: "u_gokul",
        uploadedAt: days(-1),
      },
    ],
    references: [],
    intakeScore: 74,
    createdAt: days(-9),
    updatedAt: days(-1),
  },
  {
    id: "t_7",
    reference: "GW-112",
    title: "Customer story — social carousel",
    description:
      "5-slide Instagram/LinkedIn carousel telling the Acme Corp customer story. Pull quotes + outcome stats provided.",
    businessObjective: "Build social proof and credibility with mid-market prospects.",
    status: "completed",
    priority: "medium",
    deliverableType: "social_media_post",
    department: "Marketing",
    requesterId: "u_aisha",
    contact: { name: "Aisha Verma", email: "aisha@company.com", phone: "+1 415 555 0142" },
    deadline: days(-2),
    estimatedCompletion: days(-3),
    effort: "small",
    tags: ["social", "customer-story"],
    pendingInfo: [],
    attachments: [
      {
        id: "a_5",
        name: "acme-carousel.zip",
        kind: "zip",
        sizeLabel: "8.7 MB",
        url: "#",
        uploadedBy: "u_gokul",
        uploadedAt: days(-3),
      },
    ],
    references: [],
    intakeScore: 86,
    createdAt: days(-12),
    updatedAt: days(-3),
  },
  {
    id: "t_8",
    reference: "GW-111",
    title: "Rebranded email signature template",
    description:
      "Company-wide HTML email signature matching the refreshed brand. Needs light/dark email client compatibility.",
    businessObjective: "Present a consistent, professional brand in every outbound email.",
    status: "completed",
    priority: "low",
    deliverableType: "branding",
    department: "Operations",
    requesterId: "u_daniel",
    contact: { name: "Daniel Cruz", email: "daniel@company.com" },
    deadline: days(-5),
    estimatedCompletion: days(-6),
    effort: "small",
    tags: ["branding", "email"],
    pendingInfo: [],
    attachments: [],
    references: [],
    intakeScore: 69,
    createdAt: days(-15),
    updatedAt: days(-6),
  },
  {
    id: "t_9",
    reference: "GW-110",
    title: "Old trade show poster (2023)",
    description: "Archived poster from last year's trade show. Kept for reference.",
    businessObjective: "Historical reference for event collateral style.",
    status: "archived",
    priority: "low",
    deliverableType: "poster",
    department: "Marketing",
    requesterId: "u_aisha",
    contact: { name: "Aisha Verma", email: "aisha@company.com" },
    deadline: days(-60),
    estimatedCompletion: days(-65),
    effort: "medium",
    tags: ["event", "archive"],
    pendingInfo: [],
    attachments: [],
    references: [],
    intakeScore: 72,
    createdAt: days(-90),
    updatedAt: days(-60),
  },
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: "c_1",
    taskId: "t_1",
    authorId: "u_gokul",
    body: "Starting on the hero card now. @Aisha Verma do you want the gradient on the full bleed or just behind the headline?",
    mentions: ["u_aisha"],
    parentId: null,
    isQuestion: true,
    createdAt: days(-1),
  },
  {
    id: "c_2",
    taskId: "t_1",
    authorId: "u_aisha",
    body: "Full bleed please — and keep the logo in the top-left lockup.",
    mentions: ["u_gokul"],
    parentId: "c_1",
    createdAt: days(-1),
  },
  {
    id: "c_3",
    taskId: "t_2",
    authorId: "u_gokul",
    body: "@Lena Schmidt I can't finalize the charts without the Q2 revenue numbers and the updated org chart — flagged this as Waiting for Inputs.",
    mentions: ["u_lena"],
    parentId: null,
    isQuestion: true,
    createdAt: days(-1),
  },
  {
    id: "c_4",
    taskId: "t_5",
    authorId: "u_gokul",
    body: "v2 uploaded with the CTA chip moved right. @Meera Nair ready for your review.",
    mentions: ["u_meera"],
    parentId: null,
    createdAt: days(0),
  },
];

export const SEED_ACTIVITY: ActivityEvent[] = [
  { id: "ae_1", taskId: "t_1", type: "created", actorId: "u_aisha", message: "Task created", createdAt: days(-3) },
  { id: "ae_2", taskId: "t_1", type: "priority_changed", actorId: "u_gokul", message: "Priority changed to Critical", createdAt: days(-3) },
  { id: "ae_3", taskId: "t_1", type: "status_changed", actorId: "u_gokul", message: "Moved to In Progress", createdAt: days(-1) },
  { id: "ae_4", taskId: "t_1", type: "question_asked", actorId: "u_gokul", message: "Gokul requested clarification on the gradient", createdAt: days(-1) },
  { id: "ae_5", taskId: "t_1", type: "question_answered", actorId: "u_aisha", message: "Aisha responded", createdAt: days(-1) },
  { id: "ae_6", taskId: "t_2", type: "created", actorId: "u_lena", message: "Task created", createdAt: days(-5) },
  { id: "ae_7", taskId: "t_2", type: "status_changed", actorId: "u_gokul", message: "Moved to Waiting for Inputs", createdAt: days(-1) },
  { id: "ae_8", taskId: "t_5", type: "file_uploaded", actorId: "u_gokul", message: "First draft uploaded (banner-v2.png)", createdAt: days(-1) },
  { id: "ae_9", taskId: "t_5", type: "status_changed", actorId: "u_gokul", message: "Moved to Review", createdAt: days(0) },
  { id: "ae_10", taskId: "t_7", type: "completed", actorId: "u_gokul", message: "Task completed", createdAt: days(-3) },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: "n_1",
    type: "question_asked",
    title: "Gokul asked a question",
    body: "On GW-118 — gradient placement on the hero card.",
    taskId: "t_1",
    recipientId: "u_aisha",
    read: false,
    createdAt: days(-1),
  },
  {
    id: "n_2",
    type: "task_updated",
    title: "GW-114 moved to Review",
    body: "Your banner asset is ready for review.",
    taskId: "t_5",
    recipientId: "u_meera",
    read: false,
    createdAt: days(0),
  },
  {
    id: "n_3",
    type: "task_completed",
    title: "GW-112 completed",
    body: "The Acme customer carousel is done and delivered.",
    taskId: "t_7",
    recipientId: "u_aisha",
    read: true,
    createdAt: days(-3),
  },
];
